// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpzcrngawaaeqfohlqac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwemNybmdhd2FhZXFmb2hscWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjE3NDAsImV4cCI6MjA2NzA5Nzc0MH0.7sRVZ4QsvWDmMy9jvWZ1UCrDLMz8YvGbqyZdP5mZbwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});